# Generated by Django 3.0.6 on 2020-06-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='context',
            field=models.TextField(max_length=240),
        ),
    ]
