# Generated by Django 3.0.6 on 2020-06-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_tweet_retweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='context',
            field=models.TextField(blank=True, max_length=240, null=True),
        ),
    ]
